/*
 * (c) Copyright 2005-2011 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/support/OrderByDirection.p.vm.java
 */
package org.broadleafcommerce.common.util.dao;

public enum OrderByDirection {
    ASC, DESC;
}
